config/routes.rb
Rails.application.routes.draw do
  resources :enologos
  resources :newspapers
  resources :wines
  resources :strains
  resources :strain_wines, only: [:index, :update, :destroy , :edit]
  resources :enologonewspapers, only: [:create , :destroy]
  resources :notes, only: [:create]
  root to: 'wines#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/newspaper.rb
class Newspaper < ApplicationRecord
	has_many :EnologoNewspapers, dependent: :destroy
end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController
  before_action :set_newspaper, only: [:show, :edit, :update, :destroy]

  # GET /newspapers
  # GET /newspapers.json
  def index
    @newspapers = Newspaper.all
  end

  # GET /newspapers/1
  # GET /newspapers/1.json
  def show
  end

  # GET /newspapers/new
  def new
    @newspaper = Newspaper.new
  end

  # GET /newspapers/1/edit
  def edit
  end

  # POST /newspapers
  # POST /newspapers.json
  def create
    @newspaper = Newspaper.new(newspaper_params)

    respond_to do |format|
      if @newspaper.save
        format.html { redirect_to @newspaper, notice: 'Newspaper was successfully created.' }
        format.json { render :show, status: :created, location: @newspaper }
      else
        format.html { render :new }
        format.json { render json: @newspaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newspapers/1
  # PATCH/PUT /newspapers/1.json
  def update
    respond_to do |format|
      if @newspaper.update(newspaper_params)
        format.html { redirect_to @newspaper, notice: 'Newspaper was successfully updated.' }
        format.json { render :show, status: :ok, location: @newspaper }
      else
        format.html { render :edit }
        format.json { render json: @newspaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newspapers/1
  # DELETE /newspapers/1.json
  def destroy
    @newspaper.destroy
    respond_to do |format|
      format.html { redirect_to newspapers_url, notice: 'Newspaper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newspaper
      @newspaper = Newspaper.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def newspaper_params
      params.require(:newspaper).permit(:name)
    end
end

app/helpers/newspapers_helper.rb
module NewspapersHelper
end

app/views/newspapers/_form.html.erb
<%= form_with(model: newspaper, local: true) do |form| %>
  <% if newspaper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(newspaper.errors.count, "error") %> prohibited this newspaper from being saved:</h2>

      <ul>
      <% newspaper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/newspapers/edit.html.erb
<h1>Editing Newspaper</h1>

<%= render 'form', newspaper: @newspaper %>

<%= link_to 'Show', @newspaper %> |
<%= link_to 'Back', newspapers_path %>

app/views/newspapers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Newspapers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newspapers.each do |newspaper| %>
      <tr>
        <td><%= newspaper.name %></td>
        <td><%= link_to 'Show', newspaper %></td>
        <td><%= link_to 'Edit', edit_newspaper_path(newspaper) %></td>
        <td><%= link_to 'Destroy', newspaper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newspaper', new_newspaper_path %>

app/views/newspapers/new.html.erb
<h1>New Newspaper</h1>

<%= render 'form', newspaper: @newspaper %>

<%= link_to 'Back', newspapers_path %>

app/views/newspapers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @newspaper.name %>
</p>

<%= link_to 'Edit', edit_newspaper_path(@newspaper) %> |
<%= link_to 'Back', newspapers_path %>