config/routes.rb
Rails.application.routes.draw do
  resources :enologos
  resources :newspapers
  resources :wines
  resources :strains
  resources :strain_wines, only: [:index, :update, :destroy , :edit]
  resources :enologonewspapers, only: [:create , :destroy]
  resources :notes, only: [:create]
  root to: 'wines#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/enologo.rb
class Enologo < ApplicationRecord
	has_many :EnologoNewspapers, dependent: :destroy
	has_many :notes, dependent: :destroy
	def score(wine)
		nota = Note.where(wine: wine).where(enologo: self)
		if nota.blank?
			return 0
		else
			return nota.first.score
		end
	end
end

app/controllers/enologos_controller.rb
class EnologosController < ApplicationController
  before_action :set_enologo, only: [:show, :edit, :update, :destroy]

  # GET /enologos
  # GET /enologos.json
  def index
    @enologos = Enologo.all
  end

  # GET /enologos/1
  # GET /enologos/1.json
  def show
    @cargos = ["Editor" , "Writer" , "Reviewer"]
    @newspapers = Newspaper.all
    @enologonewspapers = EnologoNewspaper.where(enologo: @enologo)
  end

  # GET /enologos/new
  def new
    @enologo = Enologo.new
  end

  # GET /enologos/1/edit
  def edit
  end

  # POST /enologos
  # POST /enologos.json
  def create
    @enologo = Enologo.new(enologo_params)

    respond_to do |format|
      if @enologo.save
        format.html { redirect_to @enologo, notice: 'Enologo was successfully created.' }
        format.json { render :show, status: :created, location: @enologo }
      else
        format.html { render :new }
        format.json { render json: @enologo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enologos/1
  # PATCH/PUT /enologos/1.json
  def update
    respond_to do |format|
      if @enologo.update(enologo_params)
        format.html { redirect_to @enologo, notice: 'Enologo was successfully updated.' }
        format.json { render :show, status: :ok, location: @enologo }
      else
        format.html { render :edit }
        format.json { render json: @enologo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enologos/1
  # DELETE /enologos/1.json
  def destroy
    @enologo.destroy
    respond_to do |format|
      format.html { redirect_to enologos_url, notice: 'Enologo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enologo
      @enologo = Enologo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enologo_params
      params.require(:enologo).permit(:name, :edad, :nacionalidad)
    end
end

app/helpers/enologos_helper.rb
module EnologosHelper
end

app/views/enologos/_form.html.erb
<%= form_with(model: enologo, local: true) do |form| %>
  <% if enologo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enologo.errors.count, "error") %> prohibited this enologo from being saved:</h2>

      <ul>
      <% enologo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :edad %>
    <%= form.text_field :edad %>
  </div>

  <div class="field">
    <%= form.label :nacionalidad %>
    <%= form.text_field :nacionalidad %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enologos/edit.html.erb
<h1>Editing Enologo</h1>

<%= render 'form', enologo: @enologo %>

<%= link_to 'Show', @enologo %> |
<%= link_to 'Back', enologos_path %>

app/views/enologos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enologos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Edad</th>
      <th>Nacionalidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enologos.each do |enologo| %>
      <tr>
        <td><%= enologo.name %></td>
        <td><%= enologo.edad %></td>
        <td><%= enologo.nacionalidad %></td>
        <td><%= link_to 'Show', enologo %></td>
        <td><%= link_to 'Edit', edit_enologo_path(enologo) %></td>
        <td><%= link_to 'Destroy', enologo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enologo', new_enologo_path %>

app/views/enologos/new.html.erb
<h1>New Enologo</h1>

<%= render 'form', enologo: @enologo %>

<%= link_to 'Back', enologos_path %>

app/views/enologos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enologo.name %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @enologo.edad %>
</p>

<p>
  <strong>Nacionalidad:</strong>
  <%= @enologo.nacionalidad %>
</p>


<% @enologonewspapers.each do |enp| %>
	<p><%= enp.newspaper.name %></p>
	<p><%= enp.cargo %></p>
	<%= link_to 'Destroy', enologonewspaper_path(enp), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>


<%= form_tag enologonewspapers_path do  %>

	<%= hidden_field_tag 'enologo', @enologo.id %>

	<%= select_tag "newspaper", options_from_collection_for_select(@newspapers, "id", "name", "1") %>

	<br>
	<% @cargos.each_with_index do |c , index| %>
		<%= check_box_tag "cargos_ids[]" , c  %>
		<label><%= "#{index + 1}) #{c}" %></label>
	<% end %>

	<%= submit_tag "Guardar" %>
	<br>
<% end %>


<%= link_to 'Edit', edit_enologo_path(@enologo) %> |
<%= link_to 'Back', enologos_path %>