config/routes.rb
Rails.application.routes.draw do
  resources :enologos
  resources :newspapers
  resources :wines
  resources :strains
  resources :strain_wines, only: [:index, :update, :destroy , :edit]
  resources :enologonewspapers, only: [:create , :destroy]
  resources :notes, only: [:create]
  root to: 'wines#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wine.rb
class Wine < ApplicationRecord
  has_many :strain_wines
  has_many :strains, through: :strain_wines, dependent: :destroy
  has_many :notes, dependent: :destroy
  validates :name, presence: true
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [:show, :edit, :update, :destroy]

  # GET /wines
  # GET /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1
  # GET /wines/1.json
  def show
    @strains = StrainWine.where(wine: @wine)
    @enologos = Enologo.all.order(:edad)
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines
  # POST /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: 'Wine was successfully created.' }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1
  # PATCH/PUT /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: 'Wine was successfully updated.' }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: 'Wine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, {strain_ids: []})
    end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :strains %>
    <%= form.collection_check_boxes(:strain_ids, Strain.all, :id, :name) do |b| %>
        <%= b.label class:"label-checkbox" do%>
            <%=b.check_box + b.text%>
        <%end%>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Strains</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td><%= wine.strains.order(:name).map{ |c| c.name.capitalize + " (" + StrainWine.where(wine: wine).where(strain:c).first.percentage.to_s + "%)" }.join(' , ')%></td>


        <td><%= wine.notes.reject{|n| n.score == 0}.map{ |n| n.enologo.name.capitalize + "(#{n.score})" }.join(' , ') %></td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
  <%= link_to 'Edit', edit_wine_path(@wine) %> |
</p>

<h1>Strain</h1>
<% @strains.each do |cepa|  %>
	<p><%= cepa.strain.name %></p>
	<p><%= cepa.percentage %>
	<%= link_to "Edit", edit_strain_wine_path(cepa) %>
	</p>
<% end %>



<h1>Notas</h1>
<ul>
<% @enologos.each do |e| %>
	<div class="field">
		<li>
			<%= e.name.capitalize %>		
			<%= form_tag notes_path do  %>
				<%= hidden_field_tag 'enologo', e.id %>
				<%= hidden_field_tag 'wine', @wine.id %>
				<%= number_field_tag :score, e.score(@wine), min:0, max:100 %> 
			<% end %>
		</li>
	</div>
<%  end %>
</ul>

<%= link_to 'Back', wines_path %>